#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

language: generic
env:
  global:
    - CONDA_PY=3.5

# disabled, because osx takes very long
#os:
#  - linux
#  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$CONDA_PY pytest pytest-cov
  - source activate test-environment
  - conda install -c conda-forge -c defaults pyqt matplotlib xarray dask numpy scipy numba netcdf4 cartopy jdcal
  - python setup.py install

script:
  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
  - export NUMBA_DISABLE_JIT=1
  # Uncomment following line if web testing on travis breaks our build
  # - export CATE_DISABLE_WEB_TESTS=1
  - export CATE_DISABLE_PLOT_TESTS=1
  - py.test -v --cov=cate test

after_success:
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION
