version: '0.7.0.dev1.{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda35-x64"
    CONDA_PY: "3.5"

install:
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda install certifi
  - cmd: conda info -a

build_script:
  - cmd: conda create -q -n test-environment python=%CONDA_PY% pytest pytest-cov
  - cmd: call %PYTHON_LOC%\Scripts\activate.bat test-environment
  - cmd: conda install -c conda-forge -c defaults pyqt matplotlib xarray dask numpy scipy numba netcdf4 cartopy jdcal
  - cmd: python setup.py install
  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
  - set NUMBA_DISABLE_JIT=1
  # Uncomment following line if web testing on travis breaks our build
  # - set CATE_DISABLE_WEB_TESTS=1
  - set CATE_DISABLE_PLOT_TESTS=1
  - py.test -v --cov=cate test
