name: cate-docs
channels:
  - conda-forge
  - defaults
dependencies:
  # rdt has currently no higher version
  - python=3.5*
  #
  # for testing
  #
  - pytest
  - pytest-cov
  - tornado
  # v 0.2.0 of sphinx-argparse needs a greater commonmark-parser version than rtd
  - sphinx-argparse ==0.1.17
  - pip:
    - sphinx_autodoc_annotation
