name: cate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6*
  #
  # for testing
  #
  - pytest
  - pytest-cov
  - flake8
  #
  # dependencies (in alphabetical order)
  #
  - cartop >=0.15
  - dask >=0.14
  - fiona >=1.7
  - geopandas >=0.2
  - jdcal >=1.3
  - matplotlib >=2.0
  - netcdf4 >=1.2
  - numba >=0.33
  # numpy 1.12 gave some trouble
  - numpy >=1.11
  # pandas 0.20 has deprecations that produce ugly warnings from xarray
  - pandas=0.19
  - pillow >=4.1
  - pyqt >=5.6
  - pyproj >=1.9
  - python-dateutil >=2.6
  - scipy >=0.19
  - shapely >=1.5
  - tornado >=4.5
  - xarray >=0.9.5
  #
  # for these packages specific version are needed, lower minor version have errors
  # they often get downgraded if not required explicitly
  - hdf4 >=4.2.12
  - geos >=3.5.1
