name: cate-docs-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6*
  #
  # for testing
  #
  - pytest
  - pytest-cov
  - tornado
  - CommonMark >=0.5.6
  - sphinx-argparse >=0.2.1
  - sphinx_rtd_theme >=0.2.4
  - pip:
    - sphinx_autodoc_annotation
