name: cate
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.5,<3.7
  #
  # for testing
  #
  - pytest
  - pytest-cov
  #
  # dependencies (in alphabetical order)
  #
  - cartopy
  - dask>=0.14
  - geopandas>=0.2
  - jdcal>=1.3
  - matplotlib>=1.5,<2
  - netcdf4>=1.2
  - numba>=0.26
  - numpy>=1.11,<2
  - pandas>=0.18
  - pillow>=4.0
  - pyqt>4,<5
  - scipy>=0.17
  - tornado>=4.4
  - xarray>=0.9.1
  #
  # for these packages specific version are needed, lower minor version have errors
  # they often get downgraded if not required explicitly
  - hdf4>=4.2.12
  - geos>=3.5.1